version: '3.7'

services:
  nginx:
    container_name: go_bp_nginx
    build: ./docker/nginx
    volumes:
      - ./:/var/www:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8200:80
      - 9200:81
    networks:
      - default
      - shared_go_bp
    depends_on:
      - go

#  go_prod:
#    hostname: api-production
#    restart: unless-stopped
#    build:
#      context: .
#      dockerfile: Dockerfile
#      target: base
#    environment:
#      PORT: "8081"
#    volumes:
#      - type: bind
#        source: .
#        target: /home/api
#    working_dir: /home/api
#    ports:
#      - "8081:8081"
#    command: bash -c "./scripts/production.sh"

  go:
    container_name: go_go
    restart: unless-stopped
    build:
      context: . 
      dockerfile: Dockerfile
      target: dev
    volumes:
      - type: bind
        source: .
        target: /home/api
    working_dir: /home/api
    ports:
      - "8180:8080"
    command: bash -c "go mod download && make serve"

  db:
    container_name: go_db
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./docker/db/data:/data/db
    expose:
      - 27017
    ports:
      - 27317:27017
    networks:
      - default

networks:
  shared_go_bp:
    name: shared_go_bp
    external: true